# Generated by Django 4.1.6 on 2023-06-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva de Banho', 'verbose_name_plural': 'Reservas de Banho'},
        ),
    ]
