# Generated by Django 4.1.6 on 2023-06-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='petshop',
        ),
        migrations.DeleteModel(
            name='Petshop',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
